//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZORBANK.Recursos_Localizables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZORBANK.Recursos_Localizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca.
        /// </summary>
        internal static string Acerca {
            get {
                return ResourceManager.GetString("Acerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda Movimientos.
        /// </summary>
        internal static string AgendaMovimientos {
            get {
                return ResourceManager.GetString("AgendaMovimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Empresa.
        /// </summary>
        internal static string AgregarEmpresa {
            get {
                return ResourceManager.GetString("AgregarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        internal static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiarios.
        /// </summary>
        internal static string Beneficiarios {
            get {
                return ResourceManager.GetString("Beneficiarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora del Sistema.
        /// </summary>
        internal static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogos.
        /// </summary>
        internal static string Catalogos {
            get {
                return ResourceManager.GetString("Catalogos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string CerrarSesión {
            get {
                return ResourceManager.GetString("CerrarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceptos.
        /// </summary>
        internal static string Conceptos {
            get {
                return ResourceManager.GetString("Conceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliación Bancaria.
        /// </summary>
        internal static string Conciliacion {
            get {
                return ResourceManager.GetString("Conciliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        internal static string Cuentas {
            get {
                return ResourceManager.GetString("Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Bancarias.
        /// </summary>
        internal static string CuentasBancarias {
            get {
                return ResourceManager.GetString("CuentasBancarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la Empresa.
        /// </summary>
        internal static string DatosEmpresa {
            get {
                return ResourceManager.GetString("DatosEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisión de Cheques.
        /// </summary>
        internal static string EmisionCheques {
            get {
                return ResourceManager.GetString("EmisionCheques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas de Pago.
        /// </summary>
        internal static string FormasPago {
            get {
                return ResourceManager.GetString("FormasPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impresoras.
        /// </summary>
        internal static string Impresoras {
            get {
                return ResourceManager.GetString("Impresoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice.
        /// </summary>
        internal static string Indice {
            get {
                return ResourceManager.GetString("Indice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monedas.
        /// </summary>
        internal static string Monedas {
            get {
                return ResourceManager.GetString("Monedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos Bancarios.
        /// </summary>
        internal static string MovimientosBancarios {
            get {
                return ResourceManager.GetString("MovimientosBancarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión Base de Datos.
        /// </summary>
        internal static string MultiBD {
            get {
                return ResourceManager.GetString("MultiBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos.
        /// </summary>
        internal static string Procesos {
            get {
                return ResourceManager.GetString("Procesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        internal static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        internal static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cambio.
        /// </summary>
        internal static string TipoCambio {
            get {
                return ResourceManager.GetString("TipoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
