//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZORBANK.net.azurewebsites.bancos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicesBancoSoap", Namespace="http://bancos.azurewebsites.net/")]
    public partial class WebServicesBanco : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCuentasBancariasXEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCuentasBancariasXBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback sEnviarDisponibilidadBancariaXCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sEnviarDisponibilidadBancariaXBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback sEnviarDisponibilidadBancariaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServicesBanco() {
            this.Url = global::ZORBANK.Properties.Settings.Default.ZORBANK_net_azurewebsites_bancos_WebServicesBanco;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ListarCuentasBancariasXEmpresaCompletedEventHandler ListarCuentasBancariasXEmpresaCompleted;
        
        /// <remarks/>
        public event ListarCuentasBancariasXBancoCompletedEventHandler ListarCuentasBancariasXBancoCompleted;
        
        /// <remarks/>
        public event sEnviarDisponibilidadBancariaXCuentaCompletedEventHandler sEnviarDisponibilidadBancariaXCuentaCompleted;
        
        /// <remarks/>
        public event sEnviarDisponibilidadBancariaXBancoCompletedEventHandler sEnviarDisponibilidadBancariaXBancoCompleted;
        
        /// <remarks/>
        public event sEnviarDisponibilidadBancariaCompletedEventHandler sEnviarDisponibilidadBancariaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/HelloWorld", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/ListarCuentasBancariasXEmpresa", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarCuentasBancariasXEmpresa(string codigo_empresa) {
            object[] results = this.Invoke("ListarCuentasBancariasXEmpresa", new object[] {
                        codigo_empresa});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuentasBancariasXEmpresaAsync(string codigo_empresa) {
            this.ListarCuentasBancariasXEmpresaAsync(codigo_empresa, null);
        }
        
        /// <remarks/>
        public void ListarCuentasBancariasXEmpresaAsync(string codigo_empresa, object userState) {
            if ((this.ListarCuentasBancariasXEmpresaOperationCompleted == null)) {
                this.ListarCuentasBancariasXEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuentasBancariasXEmpresaOperationCompleted);
            }
            this.InvokeAsync("ListarCuentasBancariasXEmpresa", new object[] {
                        codigo_empresa}, this.ListarCuentasBancariasXEmpresaOperationCompleted, userState);
        }
        
        private void OnListarCuentasBancariasXEmpresaOperationCompleted(object arg) {
            if ((this.ListarCuentasBancariasXEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuentasBancariasXEmpresaCompleted(this, new ListarCuentasBancariasXEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/ListarCuentasBancariasXBanco", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListarCuentasBancariasXBanco(string codigo_banco) {
            object[] results = this.Invoke("ListarCuentasBancariasXBanco", new object[] {
                        codigo_banco});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuentasBancariasXBancoAsync(string codigo_banco) {
            this.ListarCuentasBancariasXBancoAsync(codigo_banco, null);
        }
        
        /// <remarks/>
        public void ListarCuentasBancariasXBancoAsync(string codigo_banco, object userState) {
            if ((this.ListarCuentasBancariasXBancoOperationCompleted == null)) {
                this.ListarCuentasBancariasXBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuentasBancariasXBancoOperationCompleted);
            }
            this.InvokeAsync("ListarCuentasBancariasXBanco", new object[] {
                        codigo_banco}, this.ListarCuentasBancariasXBancoOperationCompleted, userState);
        }
        
        private void OnListarCuentasBancariasXBancoOperationCompleted(object arg) {
            if ((this.ListarCuentasBancariasXBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuentasBancariasXBancoCompleted(this, new ListarCuentasBancariasXBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/sEnviarDisponibilidadBancariaXCuenta", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet sEnviarDisponibilidadBancariaXCuenta(string codigo_cuenta) {
            object[] results = this.Invoke("sEnviarDisponibilidadBancariaXCuenta", new object[] {
                        codigo_cuenta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaXCuentaAsync(string codigo_cuenta) {
            this.sEnviarDisponibilidadBancariaXCuentaAsync(codigo_cuenta, null);
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaXCuentaAsync(string codigo_cuenta, object userState) {
            if ((this.sEnviarDisponibilidadBancariaXCuentaOperationCompleted == null)) {
                this.sEnviarDisponibilidadBancariaXCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsEnviarDisponibilidadBancariaXCuentaOperationCompleted);
            }
            this.InvokeAsync("sEnviarDisponibilidadBancariaXCuenta", new object[] {
                        codigo_cuenta}, this.sEnviarDisponibilidadBancariaXCuentaOperationCompleted, userState);
        }
        
        private void OnsEnviarDisponibilidadBancariaXCuentaOperationCompleted(object arg) {
            if ((this.sEnviarDisponibilidadBancariaXCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sEnviarDisponibilidadBancariaXCuentaCompleted(this, new sEnviarDisponibilidadBancariaXCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/sEnviarDisponibilidadBancariaXBanco", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet sEnviarDisponibilidadBancariaXBanco(string codigo_banco) {
            object[] results = this.Invoke("sEnviarDisponibilidadBancariaXBanco", new object[] {
                        codigo_banco});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaXBancoAsync(string codigo_banco) {
            this.sEnviarDisponibilidadBancariaXBancoAsync(codigo_banco, null);
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaXBancoAsync(string codigo_banco, object userState) {
            if ((this.sEnviarDisponibilidadBancariaXBancoOperationCompleted == null)) {
                this.sEnviarDisponibilidadBancariaXBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsEnviarDisponibilidadBancariaXBancoOperationCompleted);
            }
            this.InvokeAsync("sEnviarDisponibilidadBancariaXBanco", new object[] {
                        codigo_banco}, this.sEnviarDisponibilidadBancariaXBancoOperationCompleted, userState);
        }
        
        private void OnsEnviarDisponibilidadBancariaXBancoOperationCompleted(object arg) {
            if ((this.sEnviarDisponibilidadBancariaXBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sEnviarDisponibilidadBancariaXBancoCompleted(this, new sEnviarDisponibilidadBancariaXBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancos.azurewebsites.net/sEnviarDisponibilidadBancaria", RequestNamespace="http://bancos.azurewebsites.net/", ResponseNamespace="http://bancos.azurewebsites.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet sEnviarDisponibilidadBancaria() {
            object[] results = this.Invoke("sEnviarDisponibilidadBancaria", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaAsync() {
            this.sEnviarDisponibilidadBancariaAsync(null);
        }
        
        /// <remarks/>
        public void sEnviarDisponibilidadBancariaAsync(object userState) {
            if ((this.sEnviarDisponibilidadBancariaOperationCompleted == null)) {
                this.sEnviarDisponibilidadBancariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsEnviarDisponibilidadBancariaOperationCompleted);
            }
            this.InvokeAsync("sEnviarDisponibilidadBancaria", new object[0], this.sEnviarDisponibilidadBancariaOperationCompleted, userState);
        }
        
        private void OnsEnviarDisponibilidadBancariaOperationCompleted(object arg) {
            if ((this.sEnviarDisponibilidadBancariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sEnviarDisponibilidadBancariaCompleted(this, new sEnviarDisponibilidadBancariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ListarCuentasBancariasXEmpresaCompletedEventHandler(object sender, ListarCuentasBancariasXEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuentasBancariasXEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuentasBancariasXEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ListarCuentasBancariasXBancoCompletedEventHandler(object sender, ListarCuentasBancariasXBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuentasBancariasXBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuentasBancariasXBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void sEnviarDisponibilidadBancariaXCuentaCompletedEventHandler(object sender, sEnviarDisponibilidadBancariaXCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sEnviarDisponibilidadBancariaXCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sEnviarDisponibilidadBancariaXCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void sEnviarDisponibilidadBancariaXBancoCompletedEventHandler(object sender, sEnviarDisponibilidadBancariaXBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sEnviarDisponibilidadBancariaXBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sEnviarDisponibilidadBancariaXBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void sEnviarDisponibilidadBancariaCompletedEventHandler(object sender, sEnviarDisponibilidadBancariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sEnviarDisponibilidadBancariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sEnviarDisponibilidadBancariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591