//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROTOTIPO_C.C.Recursos_Localizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROTOTIPO_C.C.Recursos_Localizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string frmMPAyuda {
            get {
                return ResourceManager.GetString("frmMPAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de Datos.
        /// </summary>
        public static string frmMPBasededatos {
            get {
                return ResourceManager.GetString("frmMPBasededatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        public static string frmMPCerrarSesion {
            get {
                return ResourceManager.GetString("frmMPCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conceptos.
        /// </summary>
        public static string frmMPConceptos {
            get {
                return ResourceManager.GetString("frmMPConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        public static string frmMPDocumentos {
            get {
                return ResourceManager.GetString("frmMPDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string frmMPEmpresa {
            get {
                return ResourceManager.GetString("frmMPEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        public static string frmMPFacturas {
            get {
                return ResourceManager.GetString("frmMPFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string frmMPIdioma {
            get {
                return ResourceManager.GetString("frmMPIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresoras.
        /// </summary>
        public static string frmMPImpresoras {
            get {
                return ResourceManager.GetString("frmMPImpresoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso.
        /// </summary>
        public static string frmMPIngreso {
            get {
                return ResourceManager.GetString("frmMPIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string frmMPMenuClientes {
            get {
                return ResourceManager.GetString("frmMPMenuClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        public static string frmMPMenuConfiguracion {
            get {
                return ResourceManager.GetString("frmMPMenuConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        public static string frmMPMenuEmpleados {
            get {
                return ResourceManager.GetString("frmMPMenuEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string frmMPMenuInicio {
            get {
                return ResourceManager.GetString("frmMPMenuInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string frmMPMenuProveedores {
            get {
                return ResourceManager.GetString("frmMPMenuProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas.
        /// </summary>
        public static string frmMPMultisistemas {
            get {
                return ResourceManager.GetString("frmMPMultisistemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos.
        /// </summary>
        public static string frmMPPagos {
            get {
                return ResourceManager.GetString("frmMPPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prestamos.
        /// </summary>
        public static string frmMPPrestamo {
            get {
                return ResourceManager.GetString("frmMPPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string frmMPReportes {
            get {
                return ResourceManager.GetString("frmMPReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        public static string frmMPSeguridad {
            get {
                return ResourceManager.GetString("frmMPSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Principal.
        /// </summary>
        public static string frmMPTitulo {
            get {
                return ResourceManager.GetString("frmMPTitulo", resourceCulture);
            }
        }
    }
}
