//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasCorrientes.CuentaCorriente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuentaCorriente.WebServiceCCSoap")]
    public interface WebServiceCCSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cadena", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet cadena();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cadena", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> cadenaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCCSoapChannel : CuentasCorrientes.CuentaCorriente.WebServiceCCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCCSoapClient : System.ServiceModel.ClientBase<CuentasCorrientes.CuentaCorriente.WebServiceCCSoap>, CuentasCorrientes.CuentaCorriente.WebServiceCCSoap {
        
        public WebServiceCCSoapClient() {
        }
        
        public WebServiceCCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet cadena() {
            return base.Channel.cadena();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> cadenaAsync() {
            return base.Channel.cadenaAsync();
        }
    }
}
